lessons:
  outputs:
    dev:
      dataset: dbt_ps
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: regal-groove-434023-k5
      threads: 60
      type: bigquery
  target: dev
